name: chip-lighting-app
base: core20
type: app
version: "0.1"
summary: An example showing the use of Matter CHIP lighting app on the Linux.
description: |
  Matter (formerly Project CHIP) creates more connections between more objects, simplifying development for manufacturers 
  and increasing compatibility for consumers, guided by the Connectivity Standards Alliance.

  This snap is an experienental packaging of Matter linux lighting app.
architectures:
  - build-on: arm64
  - build-on: amd64

grade: devel
confinement: strict
assumes: [snapd2.46]

apps:
  chip-lighting-app:
    daemon: simple
    command: bin/chip-lighting-app
    plugs: [network, network-bind]

parts:
  wiring-pi:
    source: https://github.com/WiringPi/WiringPi.git
    source-branch: master
    source-depth: 1
    override-build: |
      cd wiringpi
      sudo ./build
    plugin: nil
    build-packages: [git, gcc, g++]

  chip-lighting-app:
    source: https://github.com/MonicaisHer/connectedhomeip.git
    source-branch: "lighting-app-rpi-gpio"
    source-depth: 1
    override-build: |
      git submodule update --init	

      # Remove unused large submodules
      git rm third_party/bouffalolab/repo # 7G
      git rm third_party/mbed-os/repo
      git rm third_party/ti_simplelink_sdk/repo_cc13xx_cc26xx
      git rm third_party/ti_simplelink_sdk/repo_cc32xx
      git rm third_party/silabs/matter_support
      git rm third_party/silabs/gecko_sdk
      git rm third_party/silabs/wiseconnect-wifi-bt-sdk

      # Keep only used python packages
      cp scripts/requirements.txt scripts/requirements.txt.bak
      grep -E "click|lark|stringcase" scripts/requirements.txt.bak > scripts/requirements.txt

      source scripts/activate.sh
      
      cd examples/lighting-app/linux/
      gn gen out/build
      sed -i '18s/$/ -lwiringPi/' ./examples/lighting-app/linux/out/build/obj/chip-lighting-app.ninja
      ninja -C out/build
    build-packages: [git, gcc, g++, pkg-config, libssl-dev, libdbus-1-dev, libglib2.0-dev, libavahi-client-dev, ninja-build, python3-venv, python3-dev, python3-pip, unzip, libgirepository1.0-dev, libcairo2-dev, libreadline-dev]
    organize:
      chip-lighting-app: bin/chip-lighting-app
    plugin: nil
  





